# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    # mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: BrowserStackConfig@0
  inputs:
    BrowserStackServiceEndPoint: 'BS connection'

- script: |
    cd android/testng-examples
    mvn clean 
  displayName: 'Build with Maven | Installing dependencies'

- script: |
    pwd
    cd android/testng-examples
    mvn test -P first
  displayName: 'Running the Android test'

- task: BrowserStackResults@0